### ISSUE TITLE
GlobusConnectionError with curl SSL_ERROR_SYSCALL using globus login

### ISSUE THREAD

**Issue by rgreen13** [globus/globus-cli#746]
I'd like to use the CLI to transfers files directly to my server for processing.

I issue the command `globus -v login `

I get the results:
```Globus CLI Error: A Globus Error Occurred.
error_type:       GlobusConnectionError
message:          ConnectionError on request
```

Running `curl https://auth.globus.org/p/whoami`, I get
```
 curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to auth.globus.org:443 
```

Not sure if there are any thoughts. I had seen something similar at [https://github.com/globus/globus-cli/issues/552](https://github.com/globus/globus-cli/issues/552), but that is now closed.

**Comment by kurtmckee** [comment]
Hello! I'm not able to reproduce on my side (neither the `globus -v login` nor the `curl` commands are showing SSL errors).

As a first step, I'd like to confirm the following:

1. What host is `auth.globus.org` resolving to?
2. What version of Globus CLI is installed?
3. What version of curl and OpenSSL are installed?
4. Is there a firewall that's blocking HTTPS access?

Would you run the following commands and paste the output here?

```
nslookup auth.globus.org
globus version --verbose
curl --version
curl https://www.google.com --verbose --output /dev/null
```

**Comment by rgreen13** [comment]
Results below:
nslookup auth.globus.org

```
Server:		129.1.2.2
Address:	129.1.2.2#53

Non-authoritative answer:
Name:	auth.globus.org
Address: 54.156.19.195
Name:	auth.globus.org
Address: 34.195.221.129
Server:		129.1.2.2
Address:	129.1.2.2#53

Non-authoritative answer:
Name:	auth.globus.org
Address: 54.156.19.195
Name:	auth.globus.org
Address: 34.195.221.129
```

globus version --verbose
```
Installed version:  3.10.1
Latest version:     3.10.1

You are running the latest version of the Globus CLI

Verbose Data
---
platform:
  platform: Linux-4.18.0-240.22.1.el8_3.x86_64-x86_64-with-glibc2.28
  py_implementation: CPython
  py_version: 3.9.7
  sys.executable: /opt/intel/oneapi/intelpython/latest/bin/python
  site.USER_BASE: /home/greenr/.local
modules:
  globus_cli:
    __version__: 3.10.1
    __file__: /home/greenr/.local/lib/python3.9/site-packages/globus_cli/__init__.py
    __path__: ['/home/greenr/.local/lib/python3.9/site-packages/globus_cli']
  globus_sdk:
    __version__: 3.15.0
    __file__: /home/greenr/.local/lib/python3.9/site-packages/globus_sdk/__init__.py
    __path__: ['/home/greenr/.local/lib/python3.9/site-packages/globus_sdk']
  requests:
    __version__: 2.25.1
    __file__: /opt/intel/oneapi/intelpython/latest/lib/python3.9/site-packages/requests/__init__.py
    __path__: ['/opt/intel/oneapi/intelpython/latest/lib/python3.9/site-packages/requests']
```

curl --version
```curl 7.61.1 (x86_64-redhat-linux-gnu) libcurl/7.61.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.6 libidn2/2.2.0 libpsl/0.20.2 (+libidn2/2.2.0) libssh/0.9.4/openssl/zlib nghttp2/1.33.0
Release-Date: 2018-09-05
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz brotli TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL Metalink 
```

nsloookup google.com
```Server:		129.1.2.2
Address:	129.1.2.2#53

Non-authoritative answer:
Name:	google.com
Address: 172.217.0.174
Name:	google.com
Address: 2607:f8b0:4009:80a::200e
```

curl https://www.google.com --verbose --output /dev/null
```* Rebuilt URL to: https://www.google.com/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 142.250.190.132...
* TCP_NODELAY set
* Connected to www.google.com (142.250.190.132) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, [no content] (0):
{ [1 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [15 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [4003 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [79 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, [no content] (0):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=www.google.com
*  start date: Dec 12 08:19:43 2022 GMT
*  expire date: Mar  6 08:19:42 2023 GMT
*  subjectAltName: host "www.google.com" matched cert's "www.google.com"
*  issuer: C=US; O=Google Trust Services LLC; CN=GTS CA 1C3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
} [5 bytes data]
* TLSv1.3 (OUT), TLS app data, [no content] (0):
} [1 bytes data]
* TLSv1.3 (OUT), TLS app data, [no content] (0):
} [1 bytes data]
* TLSv1.3 (OUT), TLS app data, [no content] (0):
} [1 bytes data]
* Using Stream ID: 1 (easy handle 0x559bee6264c0)
} [5 bytes data]
* TLSv1.3 (OUT), TLS app data, [no content] (0):
} [1 bytes data]
> GET / HTTP/2
> Host: www.google.com
> User-Agent: curl/7.61.1
> Accept: */*
> 
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, [no content] (0):
{ [1 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [282 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [282 bytes data]
* TLSv1.3 (IN), TLS app data, [no content] (0):
{ [1 bytes data]
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
} [5 bytes data]
* TLSv1.3 (OUT), TLS app data, [no content] (0):
} [1 bytes data]
* TLSv1.3 (IN), TLS app data, [no content] (0):
{ [1 bytes data]
* TLSv1.3 (IN), TLS app data, [no content] (0):
{ [1 bytes data]
< HTTP/2 200 
< date: Thu, 19 Jan 2023 16:30:43 GMT
< expires: -1
< cache-control: private, max-age=0
< content-type: text/html; charset=ISO-8859-1
< cross-origin-opener-policy-report-only: same-origin-allow-popups; report-to="gws"
< report-to: {"group":"gws","max_age":2592000,"endpoints":[{"url":"https://csp.withgoogle.com/csp/report-to/gws/other"}]}
< p3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
< server: gws
< x-xss-protection: 0
< x-frame-options: SAMEORIGIN
< set-cookie: 1P_JAR=2023-01-19-16; expires=Sat, 18-Feb-2023 16:30:43 GMT; path=/; domain=.google.com; Secure
< set-cookie: AEC=ARSKqsIiIvbqGoYyyuoTxfDFBtvmqAViP9lH8hRSZM4mU20k4BFa3KWlr1o; expires=Tue, 18-Jul-2023 16:30:43 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
< set-cookie: NID=511=KEMOd5CwEuOxmp0D3GIydPOm6st5TZdieb9ZiQrRSa6FB90A6-7putgiqbdwfpJqK3CCRiItPV1933l_QEojksdgtA1f_FyAhZyjgn6-cz2AUzh4YnLvp8oOsK_zHhcfFqcGWv0-1hZAbz22pyRmQDA7yTvJWfyk2Xwv-rtTEQc; expires=Fri, 21-Jul-2023 16:30:43 GMT; path=/; domain=.google.com; HttpOnly
< alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
< accept-ranges: none
< vary: Accept-Encoding
< 
{ [5 bytes data]
* TLSv1.3 (IN), TLS app data, [no content] (0):
{ [1 bytes data]
* TLSv1.3 (IN), TLS app data, [no content] (0):
{ [1 bytes data]
* TLSv1.3 (IN), TLS app data, [no content] (0):
{ [1 bytes data]
* TLSv1.3 (IN), TLS app data, [no content] (0):
{ [1 bytes data]
* TLSv1.3 (IN), TLS app data, [no content] (0):
{ [1 bytes data]
* TLSv1.3 (IN), TLS app data, [no content] (0):
{ [1 bytes data]
* TLSv1.3 (IN), TLS app data, [no content] (0):
{ [1 bytes data]
* TLSv1.3 (IN), TLS app data, [no content] (0):
{ [1 bytes data]
* TLSv1.3 (IN), TLS app data, [no content] (0):
{ [1 bytes data]
* TLSv1.3 (IN), TLS app data, [no content] (0):
{ [1 bytes data]
* TLSv1.3 (IN), TLS app data, [no content] (0):
{ [1 bytes data]
* TLSv1.3 (IN), TLS app data, [no content] (0):
{ [1 bytes data]
100 14102    0 14102    0     0   132k      0 --:--:-- --:--:-- --:--:--  132k
* Connection #0 to host www.google.com left intact
```


curl https://auth.globus.org --verbose --output /dev/null
```
* Rebuilt URL to: https://auth.globus.org/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 34.195.221.129...
* TCP_NODELAY set
* Connected to auth.globus.org (34.195.221.129) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to auth.globus.org:443 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to auth.globus.org:443 
```
